// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwwhwvltaxztremlibmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3d2h3dmx0YXh6dHJlbWxpYm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzYwOTgsImV4cCI6MjA2OTUxMjA5OH0.X8AcqtG7uVl4Ed5pxmHtLVNmkCx7jQ4K_QPO_IYi26M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});